-- Write SQL queries to perform the following tasks using the Sakila database:
-- List the number of films per category.
SELECT c.name, COUNT(ca.category_id) FROM sakila.category as c
LEFT JOIN sakila.film_category as ca ON c.category_id = ca.category_id
GROUP BY c.name ; 
-- TABLE category => category (name, category_id, last_update) 
-- TABLE number of films 

-- Retrieve the store ID, city, and country for each store.
SELECT s.store_id, ci.city_id, co.country 
FROM sakila.country as co
JOIN sakila.city AS ci ON co.country_id = ci.country_id
JOIN sakila.address AS a ON ci.city_id = a.city_id
JOIN sakila.store as s ON a.address_id = s.address_id; 

-- 1. country (country_id, country, last_update) as co 
-- 2. address (address_id, city_id, location, last_update) as a
-- 3. store (store_id, manager_staff, address_id, last_update) as s

-- Calculate the total revenue generated by each store in dollars.
SELECT st.store_id, SUM(p.amount) as total_revenue_in_dollars
FROM sakila.payment as p 
JOIN sakila.staff as s ON p.staff_id = s.staff_id
JOIN sakila.store as st ON st.store_id = s.store_id
GROUP BY st.store_id;
-- payment (payment_id,customer_id, staff_id** rental_id, amount, payment_date, last_update)
-- staff (staff_id** first_name, last_name, address_id, picture, email store_id** active, username
-- store (store_id** manager_staff, address_id, last_update) 

-- Determine the average running time of films for each category.
SELECT c.name, ROUND (AVG(f.length)) as AVG_length 
FROM sakila.category as c
JOIN sakila.film_category as ca ON c.category_id = ca.category_id
JOIN sakila.film as f ON ca.film_id = f.film_id
GROUP BY c.name 
ORDER BY AVG_length DESC; 


-- film (film_id, length, ) category (category_id, name, last_update)
-- film_category as ca (film_id, category_id, last_update)